project_name: jac
builds:
  - dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X "main.version=v{{ .Version }}"
archives:
  - format: tar.gz
    wrap_in_directory: false
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: nestoca
      name: homebrew-public
    homepage: "https://github.com/nestoca/jac"
    description: "CLI tool for managing people and groups as Infrastructure as Code"
    license: "MIT"
