# permissions for end users to view people.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: person-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jac
    app.kubernetes.io/part-of: jac
    app.kubernetes.io/managed-by: kustomize
  name: person-viewer-role
rules:
- apiGroups:
  - jac.nesto.ca
  resources:
  - people
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jac.nesto.ca
  resources:
  - people/status
  verbs:
  - get
